
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
  - name: notebook
    description: 8888 for notebook
    port: 8888
    
image:
  file: test.Dockerfile
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
